language: generic

branches:
  only:
    - master

os:
  - osx

matrix:
  include:
    - env: BUILD_OPTIONS=""
    - env: BUILD_OPTIONS="--build-from-source"
    - env: BUILD_OPTIONS="--devel"
    - env: BUILD_OPTIONS="--without-cocoa"
    - env: BUILD_OPTIONS="--without-cocoa --with-x11"
    - env: BUILD_OPTIONS="--HEAD"
  fast_finish: true

before_install:
  - brew update
  - brew install --only-dependencies Formula/emacs-plus.rb $BUILD_OPTIONS

script:
  - travis_wait brew install --ignore-dependencies Formula/emacs-plus.rb $BUILD_OPTIONS
  - brew test Formula/emacs-plus.rb
